language: node_js

node_js:
  - 8.9.0

cache:
  bundler: true
  yarn: true
  directories:
      - node_modules

before_install:
  - openssl aes-256-cbc -K $encrypted_278b576efbf2_key -iv $encrypted_278b576efbf2_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - echo -e "Host $STAGING_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo -e "Host $PRODUCTION_SERVER\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
  - export PATH="$HOME/.yarn/bin:$PATH"

before_script:
  - yarn install

script:
  - yarn run test

deploy:
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/www && git pull' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/www && yarn' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/www && npm run staging' &&
      ssh -p $PORT $USER@$STAGING_SERVER 'cd /var/www/www && pm2 startOrRestart pm2.config.js --env=staging'
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script:
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/www && git pull' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/www && yarn' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/www && npm run production' &&
      ssh -p $PORT $USER@$PRODUCTION_SERVER 'cd /var/www/www && pm2 startOrRestart pm2.config.js --env=production'
    on:
      branch: deploy
